name: patients
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_tts: ^3.8.5
  excel: ^4.0.6
  mailer: ^6.1.0
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - images/ 
   - sounds/
